# Generated by Django 5.1.2 on 2024-11-06 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ENCRYPT', 'Encrypt'), ('DECRYPT', 'Decrypt')], max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=10)),
                ('image_size', models.IntegerField()),
                ('key_size', models.IntegerField(choices=[(16, '16 Bytes'), (24, '24 Bytes'), (32, '32 Bytes')])),
                ('encryption_time', models.DurationField()),
                ('source_image', models.CharField(choices=[('png', 'PNG'), ('jpg', 'JPG'), ('gif', 'GIF')], max_length=10)),
                ('image_conversion_time', models.DurationField(blank=True, help_text='Time taken to convert image to PNG format (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('image_size__gt', 0)), name='image_size_gt_0'), models.CheckConstraint(condition=models.Q(('image_conversion_time__lt', models.F('encryption_time')), ('image_conversion_time__gt', datetime.timedelta(0))), name='conversion_time_range')],
            },
        ),
    ]
