# Generated by Django 5.1.2 on 2024-11-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ENCRYPT', 'Encrypt'), ('DECRYPT', 'Decrypt')], max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=10)),
                ('image_size', models.PositiveIntegerField(help_text='Size of the image in bytes')),
                ('encryption_time', models.DurationField(help_text='Time taken for the encryption or decryption process')),
                ('source_image', models.CharField(choices=[('png', 'PNG'), ('jpg', 'JPG'), ('gif', 'GIF')], max_length=10)),
                ('image_conversion_time', models.DurationField(blank=True, help_text='Time taken to convert image to PNG format (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
