# Generated by Django 5.1.2 on 2024-11-05 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobox', '0002_alter_encryptionlog_encryption_time_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='encryptionlog',
            constraint=models.CheckConstraint(condition=models.Q(('image_size__gt', 0)), name='image_size_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='encryptionlog',
            constraint=models.CheckConstraint(condition=models.Q(('image_conversion_time__lt', models.F('encryption_time')), ('image_conversion_time__gt', datetime.timedelta(0))), name='conversion_time_range'),
        ),
    ]
