# Generated by Django 5.1.2 on 2024-11-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobox', '0003_encryptionlog_image_size_gt_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptionlog',
            name='key_size',
            field=models.IntegerField(choices=[(16, '16 Bytes'), (24, '24 Bytes'), (32, '32 Bytes')], default=24),
            preserve_default=False,
        ),
    ]
